bigint was added
Dmozze/first-term pull request #4
Opened 2020-07-06 10:23 UTC by Dmozze

2020-07-06 23:21 UTC, kt-cpp requested changes

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.h
> +    [[nodiscard]] uint32_t get_digit(size_t index) const;
[semantic] Зачем `[[nodiscard]]`?

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    shrink_to_fit();
[performance] Зачем вызывать эту функцию?

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    data.push_back(a & UINT32_MAX);
[semantic, minor] Лучше использовать `static_cast`, чтобы взять младшие биты

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer &res = (*this);
[style] Зачем эта переменная, если можно явно использовать *this?

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        res = res.mul_by_uint32_t(10) + (int) (i - '0');
[style, minor] c-style cast

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    shrink_to_fit();
[semantic, safety] Добавь обработку невалидных строчек и поддержку префиксного '+'

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
[performance] По коду есть множество мест, где этот метод вызывается в цикле. 

- Почти во всех случаях, вызов этого метода -- лишняя индирекция к `push_back`
- Если вызывать `push_back` в цикле, то вектор будет совершать ненужные переаллокации.

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
[performance] Почти во всех случаях этот метод является индирекцией для обращения по индексу. В участках кода, которые вызываются очень часто (например, в умножении), это замедлит работу.

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return temp;
[style] Зачем нужен этот метод?

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
[performance, style] Я так понимаю, не зашло по времени? :)
Не нужно оставлять неиспользуемый код в программе. Либо удали этот метод, либо как-нибудь используй в умножении за квадрат (например, до какого-то размера будет работать Карацуба, а дальше квадратом)

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return result;
[performance] Это умножение работает медленно. Его можно ускорить, если написать явно цикл вместо +=. Компилятор хорошо ускорит код без лишних индирекций.

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    this_abs = abs(this_abs);
[safety] Метод не обеспечивает строгую гарантию исключений.

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                ((((static_cast<unsigned __int128>(1) * r.get_digit(n + k)) << BIT_DEPTH) + r.data[n + k - 1])
[style] Сложная строчка, разбей на части её, пожалуйста

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer &big_integer::operator&=(big_integer const &rhs) {
[style] У этой и следующих функций можно вынести общий код, используя указатели на функцию или лямбда-выражения

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        res.push_back((char) (cur + '0'));
[style] c-style cast

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return static_cast<uint32_t>(-sign);
[semantic] Лучше явно использовать константы вместо арифметичеких операций с bool

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +void big_integer::set_sign() {
[style, minor] Этот метод всегда предшествует `shrink_to_fit`

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = bool(data.back() >> 31);
[style] c-style cast, лучше не кастить к bool

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer res;
[safety] Не рассмотрен случай деления на 0

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        temp = temp * static_cast<uint64_t>(UINT32_MAX + 1ll) + get_digit(i);
[performance, minor] Это умнжение можно заменить сдвигом

2020-07-06 23:21 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
[semantic] Интересно, как можно получить переполнение в длинной арифметике?

2020-07-07 19:33 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    shrink_to_fit();
Вопрос всё ещё актуален

2020-07-07 19:36 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    shrink_to_fit();
[minor] Пустая строчка -- это допустимая строка?

2020-07-07 19:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return result;
Умножение всё ещё можно разгонять, там в цикле постоянно создаётся лишняя копия
Но ладно, это необязательно фиксить

2020-07-07 20:08 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    this_abs = abs(this_abs);
Вопрос всё ещё актуален
Поясню: this_abs это ссылка на *this. Следующей сточкой ты берёшь модуль от *this. Дальше там следуют всякие умножения и копии, которые в теории могут бросить из-за выделения памяти. В случае исключения *this не вернётся к старому значению

2020-07-07 20:19 UTC, kt-cpp requested changes

2020-07-07 20:19 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer right_r = copy(right, 0, std::min(ndiv2, right.data.size()));
[note] Я думаю, можно ускорить Карацубу, если работать не с копиями биг интежера, а с указателями в векторе.
Тем не менее, это уже нетривиальный алгоритм умножения, молодец, что реализовал его (и даже с приемлимой скоростью)
Не обязательно к фиксу

2020-07-07 20:19 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    /* std::string l_l = to_string(left_l);
[style, minor] Дебаг код нужно убирать перед релизными коммитами

2020-07-07 20:19 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer &big_integer::common_fun_bits(big_integer const &rhs, const std::function<size_t(size_t, size_t)> &fn) {
[semantic] А зачем `size_t`?

2020-07-07 20:19 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (ptrdiff_t index = std::max(a.data.size(), b.data.size()); index >= 0; index--) {
[style] ворнинги можно убрать, если использовать `size_t`
Hint: у него определено переполнение

2020-07-07 23:43 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (size_t index = std::max(a.data.size(), b.data.size()); index + 1 > index; index--) {
[note]
```suggestion
    for (size_t index = std::max(a.data.size(), b.data.size()) - 1; index > 0; index--) {
```

2020-07-07 23:45 UTC, kt-cpp commented
Три старых комментария не исправлены

2020-07-09 09:21 UTC, Dmozze commented on bigint/big_integer.cpp
> +    shrink_to_fit();
Можно подробнее, пожалуйста?

2020-07-09 11:30 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    shrink_to_fit();
А, у тебя 0 соответствует пустому вектору, я не заметил изначально этого инварианта.
Вопрос снимается.

2020-07-09 11:30 UTC, kt-cpp approved these changes

2020-07-09 11:31 UTC, merged