bigint-opt was added with vector and updated CmakeList
Dmozze/first-term pull request #5
Opened 2020-07-07 22:27 UTC by Dmozze

2020-07-08 09:39 UTC, sorokin commented
```
    std::array<uint32_t, SMALL_SIZE> small_array{};
    std::shared_ptr<std::vector<uint32_t> > big_array;
```

У вас же `small_array` используется только если `is_small`, а `big_array` только если `!is_small`? Можете пожалуйста сделать из них union.

2020-09-17 22:26 UTC, kt-cpp requested changes

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    static const size_t SMALL_SIZE = 32;
* `const` -> `constexpr` иначе формально нельзя использовать эту переменную как длину массива или параметр шаблона
* 1024 байта не выглядит сильно _small_  как по мне

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    typedef std::shared_ptr<std::vector<uint32_t> > big_array;
[minor] `typedef`, а не `using` в 2к20?..

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    bool is_small;
* У нас с++11, так что `variant` нельзя пока использовать
* `variant` и так знает какую альтернативу он использует, зачем флаг `is_small`?

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/CMakeLists.txt
> -set(CMAKE_CXX_STANDARD 11)
Ай ай ай у нас в первом семестре 11 стандарт

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.h
> +class vector {
* [note] Лучше бы ему дать имя отличное от стандартного класса
* [minror] Публичные методы и члены принято ставить в начале объявления класса

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    if (std::get<big_array>(storage).unique()) return;
[minor] Можно не экономить на фигурных скобках?..

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +void vector::split() {
[minor] Сюда бы ассёрт на то, что мы сейчас big, иначе контракт функции не понятен

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    }
* [minor] Странный пробелы вокруг скобок
* У вектора есть конструктор от размера, хотя судя по коду лучше конструктор от двух итераторов
* `(*x).y` -> `x->y` Таких много по коду, найди все сам

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        (*std::get<big_array>(storage)).resize(x);
Комментарий выше про конструктор вектора

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +}
* Судя по логике кода, можно просто почленно скопировать другой вектор
* Если другой вектор стал big, но по факту в нём мало элементов, то нет смысла тоже быть big, если можно аккуратно без хипа скопировать его элементы себе в `small_array`

2020-09-17 22:26 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    return is_small ? std::get<small_array>(storage)[size_ - 1] : (*std::get<big_array>(storage)).back();
[minor] https://en.cppreference.com/w/cpp/container/array/back

2020-12-07 19:19 UTC, kt-cpp requested changes
Осталось совсем не много

2020-12-07 19:19 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +    }
У вектора есть конструктор от двуз итераторов, чтобы не делать это руками

2020-12-07 19:19 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +    }
Нет никакой причины тут делать их оба big. `shared_ptr` вполне умеет делать копии без исключений для такого

2020-12-07 19:19 UTC, kt-cpp commented on bigint-optimized/my_vector.cpp
> +    }
А кто вызовет resize у вектор если был big? Пушбекать потом в него не очень безопасно

2020-12-08 09:08 UTC, kt-cpp approved these changes

2020-12-08 13:25 UTC, merged